name: ML CI Workflow

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/pemujacoding/medical_cost_model.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlproject-env
        auto-activate-base: false

    - name: Run ML Training
      run: |
        mlflow run MLProject

    # =========================
    # ðŸ”¥ AMBIL RUN_ID TERAKHIR
    # =========================
    - name: Get latest MLflow run id
      id: get_run
      run: |
        RUN_ID=$(mlflow runs list --max-results 1 --output json | jq -r '.[0].run_id')
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    # =========================
    # BUILD DOCKER DARI MODEL
    # =========================
    - name: Build Docker Image
      run: |
        mlflow models build-docker \
          -m runs:/$RUN_ID/model \
          -n ${{ secrets.DOCKER_USERNAME }}/medical_cost_image

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/medical_cost_image:latest
