name: ML CI Workflow

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    env:
      MLFLOW_TRACKING_URI: https://dagshub.com/pemujacoding/medical_cost_model.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlproject-env
        auto-activate-base: false

    - name: Run ML Training
      run: |
        python MLProject/modelling.py

    - name: Read MLflow Run ID
      run: |
        RUN_ID=$(cat run_id.txt)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Using Run ID: $RUN_ID"

    - name: Build Docker Image from MLflow Run
      run: |
        mlflow models build-docker \
          -m runs:/$RUN_ID/online_model \
          -n ${{ secrets.DOCKER_USERNAME }}/medical_cost_image

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          -u "${{ secrets.DOCKER_USERNAME }}" \
          --password-stdin

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/medical_cost_image:latest
