name: ML CI Workflow

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: MLProject/conda.yaml
        activate-environment: mlproject-env

    - name: Run ML Training
      run: |
        python MLProject/modelling.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/online_sgd_model.joblib


    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: |
        mlflow models build-docker -m MLProject/online_model -n ${{ secrets.DOCKER_USERNAME }}/medical_cost_image

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/medical_cost_image:latest
